version: "3.9"
services:
  #######
  # Verifier Backend
  #######
  plurality-verifier-be:
    container_name: plurality-verifier-be
    build:
      context: ./verifier-backend
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_URL: ${MONGO_URL}
      PORT: ${VERIFIER_BACKEND_PORT}
      BASE_URL: ${VERIFIER_BACKEND_URL}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
    ports:
      - ${VERIFIER_BACKEND_PORT}:${VERIFIER_BACKEND_PORT}
    restart: always
    networks:
      - plurality-verifier-network
  #######
  # Verifier UI
  #######
  plurality-verifier-ui:
    container_name: plurality-verifier-ui
    build:
      context: ./verifier-ui
      dockerfile: Dockerfile
    environment:
      REACT_APP_SEMAPHORE_IDENTITY_CONTRACT: ${SEMAPHORE_IDENTITY_CONTRACT}
      REACT_APP_ETHEREUM_NETWORK: ${ETHEREUM_NETWORK}
      REACT_APP_INFURA_API_KEY: ${INFURA_API_KEY}
      REACT_APP_SIGNER_PRIVATE_KEY: ${VERIFIER_WALLET_PRIVATE_KEY}
      REACT_APP_GROUP_ID: ${GROUP_ID}
      REACT_APP_API_BASE_URL: ${VERIFIER_BACKEND_URL}
      REACT_APP_DAPP_PROOF_NAME: ${PROOF_NAME}
      REACT_APP_DAPP_NAME: ${DAPP_NAME}
      REACT_APP_IDENTITY_EVENT_NAME: ${IDENTITY_EVENT}
      REACT_APP_PROOF_EVENT_NAME: ${PROOF_EVENT}
      GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP}
    ports:
      - ${VERIFIER_UI_PORT}:${VERIFIER_UI_PORT}
    depends_on:
      - plurality-verifier-be
    restart: always
    networks:
      - plurality-verifier-network
  #######
  # Ingress
  #######
  ingress:
    container_name: ingress
    image: nginx:1.15.10-alpine
    ports:
      - target: 80
        published: 8080 # walletkit and issuer ui publish port
        protocol: tcp
        mode: host
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf # API gateway configuration
    networks:
      - plurality-verifier-network
networks:
  plurality-verifier-network:
