version: "3.9"
services:
  #######
  # Verifier Backend
  #######
  plurality-verifier-be:
    build:
      context: ./verifier-backend
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_URL: 'mongodb+srv://plurality:jYTzrK8p5dnOx1L3@cluster0.fpzntym.mongodb.net/?retryWrites=true&w=majority'
      PORT: 5000
    ports:
      - 5000:5000
    restart: always
  #######
  # Verifier UI
  #######
  plurality-verifier-ui:
    build:
      context: ./verifier-ui
      dockerfile: Dockerfile
    environment:
      REACT_APP_SEMAPHORE_IDENTITY_CONTRACT: '0xe8758638fD2E34f230b99e9b6D8587508B6D90EA'
      REACT_APP_ETHEREUM_NETWORK: 'sepolia'
      REACT_APP_INFURA_API_KEY: 'af3011fda8544efaad7252557d39befa'
      REACT_APP_SIGNER_PRIVATE_KEY: '395b681d8f9b4bb0719017ca40adb6017e3b555abc5277a107041ffcbac409d6'
      REACT_APP_DB_CONN_STRING: 'mongodb+srv://plurality:plurality@cluster0.fpzntym.mongodb.net/?retryWrites=true&w=majority'
      REACT_APP_GROUP_ID: '55'
      REACT_APP_API_BASE_URL: 'http://localhost:5000'
      REACT_APP_DAPP_PROOF_NAME: 'Plurality Verifier - Lending Test Platform dApp Proof'
      REACT_APP_IDENTITY_EVENT_NAME: 'receive_identity_request_from_web_page'
      REACT_APP_PROOF_EVENT_NAME: 'receive_proof_request_from_web_page'
    ports:
      - 3000:3000
    depends_on:
      - plurality-verifier-be
    restart: always